version: '3.8'


services:
  chatbot:
    #build: .
    image: wendeelau/chatbotbackend
    environment:
      - TLG_ACCESS_TOKEN=${TLG_ACCESS_TOKEN}
      - GPT_BASICURL=https://genai.hkbu.edu.hk/general/rest
      - GPT_MODELNAME=gpt-4-o-mini
      - GPT_APIVERSION=2024-05-01-preview
      - GPT_ACCESS_TOKEN=${GPT_ACCESS_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "80:8000"
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass $${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # volumes: 
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf
    #   - redis_data:/data
    # #command: ["/usr/local/etc/redis/redis.conf"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    # # 
    # #command: redis-server --requirepass $${REDIS_PASSWORD}
    # ports:
    #   - "6379:6379"

volumes:
  redis_data:

