services:
  - type: web
    name: chatbot
    runtime: docker
    image: wendeelau/chatbotbackend:latest
    plan: free
    envVars:
      - key: GPT_BASICURL
        value: https://genai.hkbu.edu.hk/general/rest
      - key: GPT_MODELNAME
        value: gpt-4-o-mini
      - key: GPT_APIVERSION
        value: 2024-05-01-preview
      - key: TLG_ACCESS_TOKEN
        sync: false
        value: your_telegram_token_here
      - key: GPT_ACCESS_TOKEN
        sync: false
        value: your_openai_key_here
      - key: MONGODB_URI
        sync: false
        value: your_mongodb_uri_here
      - key: SPOONACULAR_API_KEY
        sync: false
        value: your_spoonacular_key_here
      - key: REDIS_HOST
        value: ${services.redis.host}
      - key: REDIS_PORT
        value: ${services.redis.port}
      - key: REDIS_PASSWORD
        sync: false
        value: your_redis_password_here
    disk:
      name: chatbot-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /healthcheck
    serviceLinks:
      - type: redis
        name: redis

  - type: redis
    name: redis
    plan: free
    envVars:
      - key: REDIS_PASSWORD
        sync: false
        value: your_redis_password_here