services:
  - type: web
    name: chatbot
    runtime: docker
    # 必须关联代码库（用于自动构建）
    repo: https://github.com/WendeeLau/comp7940-proj-chatbot.git
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: GPT_BASICURL
        value: https://genai.hkbu.edu.hk/general/rest
      - key: GPT_MODELNAME
        value: gpt-4-o-mini
      - key: GPT_APIVERSION
        value: 2024-05-01-preview
      # 敏感变量通过 Dashboard 设置（不要硬编码）
      - key: TLG_ACCESS_TOKEN
        sync: false  # 关闭同步，避免覆盖
        value: placeholder  # 占位值（实际值在 Dashboard 设置）
      - key: GPT_ACCESS_TOKEN
        sync: false
        value: placeholder
      - key: MONGODB_URI
        sync: false
        value: placeholder
      - key: SPOONACULAR_API_KEY
        sync: false
        value: placeholder
      # Redis 配置（使用 Render 的占位符）
      - key: REDIS_HOST
        value: ${services.redis.host}
      - key: REDIS_PORT
        value: ${services.redis.port}
      - key: REDIS_PASSWORD
        value: ${services.redis.password}  # 如果 Redis 设置了密码
    disk:
      name: chatbot-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /healthcheck

  - type: redis
    name: redis
    plan: free
    # # Redis 密码配置（Render 专用字段）
    # envVars:  # Render 最新版本允许 Redis 使用 envVars
    #   - key: REDIS_PASSWORD
    #     sync: false  # 安全提示：sync 设为 false，避免明文暴露
    #     value: your_redis_password_here  # 占位值，实际值在 Dashboard 设置