services:
  - type: worker
    name: Chatbot_YumBuddy_comp7940
    region: singapore
    #runtime: image
    runtime: docker
    #image: 
    #  url: docker.io/wendeelau/chatbot-yumbuddy-com7940:v1.6
    repo: https://github.com/WendeeLau/comp7940-proj-chatbot
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: GPT_BASICURL
        value: https://genai.hkbu.edu.hk/general/rest
      - key: GPT_MODELNAME
        value: gpt-4-o-mini
      - key: GPT_APIVERSION
        value: 2024-05-01-preview
      # secret
      - key: TLG_ACCESS_TOKEN
        sync: false
      - key: GPT_ACCESS_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SPOONACULAR_API_KEY
        sync: false
      # Redis conn info
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis-chatbot
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis-chatbot
          property: port
    #healthCheckPath: /healthcheck

  - type: redis
    name: redis-chatbot
    region: singapore
    plan: free
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: all IP
    maxmemoryPolicy: allkeys-lru
