name: deploy to render and build image 

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker image build and push
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/comp7940-chatbot-yumbuddy:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/comp7940-chatbot-yumbuddy:${{ github.sha }}

      # Render deploy
      - name: Deploy on render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
      
      # Telegram notice
      - name: Send Telegram Notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            EMOJI="✅"
            STATUS="succeeded"
          else
            EMOJI="❌"
            STATUS="failed"
          fi

          MESSAGE="$EMOJI CI/CD Pipeline $STATUS
          - Repository: ${{ github.repository }}
          - Workflow: ${{ github.workflow }}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
