name: Deploy to Render with Notifications

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Deploy to Render
    #   id: deploy
    #   uses: render-oss/deploy-render@v1
    #   with:
    #     api-key: ${{ secrets.RENDER_API_KEY }}
    #     service-id: ${{ secrets.RENDER_SERVICE_ID }}

    - name: Trigger Render Deploy
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"serviceId":"${{ secrets.RENDER_SERVICE_ID }}"}' \
        https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys


    - name: Send Telegram Success
      if: success()
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ deploy seccess！
          ▶️ service: ${{ secrets.RENDER_SERVICE_NAME }}
          🕒 time: ${{ steps.deploy.outputs.deploy-time }}
          🔗 check: ${{ steps.deploy.outputs.deploy-url }}

    - name: Send Email Success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ success - ${{ github.repository }}"
        body: |
          deploy successfully on Render
          time: ${{ steps.deploy.outputs.deploy-time }}
          details: ${{ steps.deploy.outputs.deploy-url }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: "Deploy Bot <deploy@example.com>"

    - name: Send Telegram Failure
      if: failure()
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ failed！
          ▶️ service: ${{ secrets.RENDER_SERVICE_NAME }}
          🔍 logs: ${{ steps.deploy.outputs.logs-url }}

    - name: Send Email Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "❌ failed - ${{ github.repository }}"
        body: |
          deploy on Render failed！
          submit: ${{ github.sha }}
          logs: ${{ steps.deploy.outputs.logs-url }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: "Deploy Bot <deploy@example.com>"